# Generated by Django 5.1 on 2024-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='gmail_id',
            new_name='group_id',
        ),
        migrations.AddField(
            model_name='emails',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
