# Generated by Django 5.1 on 2024-12-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_rename_gmail_id_group_group_id_emails_message_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
    ]
