# Generated by Django 5.1 on 2024-09-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_emailaddress_group_gmail_id_group_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('email_address', models.ForeignKey(on_delete=models.CASCADE, to='mailing.EmailAddress')),
            ],
        ),
    ]
