# Generated by Django 5.1 on 2024-12-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_email_attachments_email_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='time_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
